name: jvc-tecnofrio-api

services:
  jvc-tecnofrio-api:
    build: .
    container_name: jvc-tecnofrio-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=SistemaInventario;User Id=sa;Password=F90XAg3aiF£7;TrustServerCertificate=True;
    ports:
      - "5000:8080"
    restart: always
    networks:
      - mssql_network

networks:
  mssql_network:
    external: true
