name: jvc-electroestilo-api

services:
  jvc-electroestilo-api:
    build: .
    container_name: jvc-electroestilo-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mssql-db;Database=electro-estilo;User Id=sa;Password=F90XAg3aiF£7;TrustServerCertificate=True;
      - Factus__UrlApi=https://api-sandbox.factus.com.co
      - Factus__ClientId=9fc8e8e1-3241-4fa1-845c-bce91aa6784f
      - Factus__ClientSecret=BeDJPX6brLjsBAKit07E0ZccKvNqEd2xlPir2JKu
      - Factus__Email=sandbox@factus.com.co
      - Factus__Password=sandbox2024%
    ports:
      - "5002:8080"
    restart: always
    networks:
      - mssql_network

networks:
  mssql_network:
    external: true
