name: jvc-tecnofrio-api

services:
  jvc-tecnofrio-api:
    build: .
    container_name: jvc-tecnofrio-api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "5000:8080"
    restart: always
    networks:
      - mssql_network

networks:
  mssql_network:
    external: true
